### ISSUE TITLE
Is there a way to specify the container name when using docker:start?

### ISSUE THREAD

**Issue by tarand** [fabric8io/docker-maven-plugin#555]
Using the docker-maven-plugin the created container is automaticall started during the maven call (if docker:start goal is specified).

In my tests, the started container is assigned an arbitrary name, just if you execute the "docker run" command without specifying --name.

I didn't find a configuration option to tell the docker-maven-plugin which value to be usage as --name. Is there such an option?

**Comment by Gmanweb** [comment]
Had the same problem and solved by just calling `docker:build` instead, then start the container with your name like `docker run --name containername -p PORT:PORT -t [REPOSITORY[:TAG]]`.  

hope this helps.

**Comment by jgangemi** [comment]
you can set the `alias` field in the pom and that will be used as the container name.

**Comment by tarand** [comment]
You mean in the <run> section for the plugin, as
...
<run>
    ....
    <network>
		<alias>mywildfly</alias>
     </network>
</run>
Just tried that, but the result is still the same (name=happy_agnesi)
???

**Comment by jgangemi** [comment]
sorry - you need to set the `alias` in the pom and also set `namingStrategy` in the `run` section to `alias`. see here: https://dmp.fabric8.io/#docker:start

**Comment by tarand** [comment]
That made it!! Thanks a lot!
